version: 2
updates:
  - package-ecosystem: github-actions
    directory: .
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: tests
    schedule:
      interval: daily
    groups:
      actions:
        patterns:
          - "*"
