name: Cs
on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: ci-cs
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Custom CS
      uses: ./
      with:
          kernel-url: https://github.com/AcmeUI-Devices/android_kernel_xiaomi_cas
          kernel-dir: cs
          kernel-branch: taffy
          config: cas_defconfig
          arch: arm64
          aosp-gcc: true
          other-clang-url: https://kali.download/nethunter-images/toolchains/google_clang-10.0.4.tar.xz
          other-gcc32-url: https://kali.download/nethunter-images/toolchains/google_armhf-4.9.tar.xz
          other-gcc64-url: https://kali.download/nethunter-images/toolchains/google_aarch64-4.9.tar.xz
          ksu: true
          ksu-version: main
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          android-version: 12
          aosp-clang-version: r416183b
          disable-lto: true
          disable_cc_werror: true
          anykernel3: true
