name: Custom
on:
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/check.yml
  ci-test:
    needs:
      - lint
    name: ci-custom
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Custom CI
      uses: ./
      with:
          kernel-url: https://github.com/AcmeUI-Devices/android_kernel_xiaomi_cas
          kernel-dir: custom
          kernel-branch: taffy
          config: cas_defconfig
          arch: arm64
          extra-cmd: LLVM=1
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          android-version: 12
          aosp-clang-version: r416183b
          disable-lto: true
          disable_cc_werror: true
          anykernel3: true
