name: fyj
on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [yaml, shellcheck, shfmt]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        if: matrix.check == 'yaml'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install YAML Lint
        if: matrix.check == 'yaml'
        run: npm install yaml-lint

      - name: Check YAML Syntax
        if: matrix.check == 'yaml'
        run: npx yaml-lint action.yml

      - name: ShellCheck Lint
        if: matrix.check == 'shellcheck'
        uses: ludeeus/action-shellcheck@2.0.0

      - name: Download and Run shfmt
        if: matrix.check == 'shfmt'
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          SHFMT_VERSION=v3.8.0
          case $(dpkg --print-architecture) in
            armv7* | armv8l | armhf | arm) ARCH=arm ;;
            i*86 | x86) ARCH=x86 ;;
            amd64 | x86_64) ARCH=amd64 ;;
            aarch64 | arm64) ARCH=arm64 ;;
            *) echo "Unknown CPU architecture!" && exit 1 ;;
          esac
          aria2c -s 16 -x 16 -o shfmt https://github.com/mvdan/sh/releases/download/${SHFMT_VERSION}/shfmt_${SHFMT_VERSION}_linux_${ARCH}
          chmod +x shfmt
          ./shfmt -w -i 2 ksupatch.sh

      - name: Clean Workspace
        run: git clean -dxf

  ci-mmp:
    strategy:
      fail-fast: false
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Mmp CI
        uses: Fyg369/Kernel-Action@main
        with:
          kernel-url: https://github.com/Fyg369/mcd_kernel_oneplus_sdm845
          kernel-dir: mmp
          kernel-branch: mcd-OOS-R
          config: mcd_ksu_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          disable_cc_werror: true
          lxc: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          ccache: true
          anykernel3: true
