name: Ksu
on:
  workflow_dispatch:

jobs:
  ci-test:
    name: ci-ksu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Ksu CI
      uses: ./
      with:
          kernel-url: https://github.com/Fyj69/mcd_kernel_oneplus_sdm845
          kernel-dir: ksu
          kernel-branch: mcd-OOS-R
          config: mcd_ksu_defconfig
          arch: arm64
          extra-cmd: LLVM=1
          aosp-gcc: true
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          ksu: true
          ksu-version: next
          ksu-other: true
          ksu-url: https://github.com/rifsxd/KernelSU-Next
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          anykernel3: true
