name: Mmp
on:
  workflow_dispatch:

jobs:
  ci-test:
    name: ci-mmp
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Mmp CI
      uses: ./
      with:
          kernel-url: https://github.com/Fyj69/kernel_oneplus_sdm845
          kernel-dir: mmp
          kernel-branch: oos/11.0
          config: sdm845-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r416183b
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          anykernel3: true
