name: Mmp
on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: ci-mmp
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Mmp CI
      uses: ./
      with:
          kernel-url: https://github.com/Fyg369/mcd_kernel_oneplus_sdm845
          kernel-dir: mmp
          kernel-branch: mcd-OOS-R
          config: mcd_ksu_defconfig
          arch: arm64
          extra-cmd: LLVM=1
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          other-gcc32-url: https://github.com/pomelohan/linux_arm-eabi-gcc
          other-gcc32-branch: master
          other-gcc64-url: https://github.com/pomelohan/linux_aarch64-elf-gcc
          other-gcc64-branch: master
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r416183b
          disable-lto: true
          disable_cc_werror: true
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          anykernel3: true
