name: mmp
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: Install dependence
        run: sudo npm i -g yaml-lint

      - name: Check yaml
        run: /usr/local/lib/node_modules/yaml-lint/dist/cli.js action.yml

      - name: Clean Workspace
        run: git clean -dxf

  sh-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint: [shellcheck, shfmt]

    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck lint
        if: matrix.lint == 'shellcheck'
        uses: ludeeus/action-shellcheck@2.0.0

      - name: shfmt lint
        if: matrix.lint == 'shfmt'
        run: |
            export HOST_ARCH=$(dpkg --print-architecture)
            case ${HOST_ARCH} in
                armv7* | armv8l | armhf | arm) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_arm -o shfmt ;;
                i*86 | x86) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_x86 -o shfmt ;;
                amd64 | x86_64) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64 -o shfmt ;;
                aarch64 | arm64) aria2c https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_arm64 -o shfmt ;;

                *) echo "Unknow cpu architecture for this device !" && exit 1 ;;
            esac
            chmod 755 -R ./shfmt
            ./shfmt -w -i 2 ksupatch.sh

      - name: Clean Workspace
        run: git clean -dxf

  ci-mmp:
    strategy:
      fail-fast: false
    needs:
      - yaml-check
      - sh-check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Mmp CI
      uses: Fyg369/Kernel-Action@main
      with:
          kernel-url: https://github.com/Fyg369/mcd_kernel_oneplus_sdm845
          kernel-dir: mmp
          kernel-branch: mcd-OOS-R
          config: mcd_ksu_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          disable_cc_werror: true
          lxc: true
          apatch: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          ccache: true
          anykernel3: true
