name: Np
on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: ci-np
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Np CI
      uses: ./
      with:
          kernel-url: https://github.com/Fyg369/android_kernel_oneplus6
          kernel-dir: np
          kernel-branch: development
          config: nethunter_ksu_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          disable_cc_werror: true
          lxc: true
          bbrplus: true
          ccache: true
          anykernel3: true
